// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLVtQ0eThYPYJlDaQ8pHnprLJeD85YDG8',
    appId: '1:757029668858:web:49346339bae3908cc44643',
    messagingSenderId: '757029668858',
    projectId: 'chatapp-61b62',
    authDomain: 'chatapp-61b62.firebaseapp.com',
    databaseURL: 'https://chatapp-61b62-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-61b62.appspot.com',
    measurementId: 'G-QJN9SCG1QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsV2z8nmmI28CvU-o_V3VBc141f1oQ5Uw',
    appId: '1:757029668858:android:eea10334352c0345c44643',
    messagingSenderId: '757029668858',
    projectId: 'chatapp-61b62',
    databaseURL: 'https://chatapp-61b62-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-61b62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSgiO-Dvg7eZ6EQpX9EZhHFydNZwZH1Y',
    appId: '1:757029668858:ios:8fd92d39e8e0b15cc44643',
    messagingSenderId: '757029668858',
    projectId: 'chatapp-61b62',
    databaseURL: 'https://chatapp-61b62-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-61b62.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANSgiO-Dvg7eZ6EQpX9EZhHFydNZwZH1Y',
    appId: '1:757029668858:ios:85faf55208b5e227c44643',
    messagingSenderId: '757029668858',
    projectId: 'chatapp-61b62',
    databaseURL: 'https://chatapp-61b62-default-rtdb.firebaseio.com',
    storageBucket: 'chatapp-61b62.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
